### ISSUE TITLE
AlphaCutter fails for some PDBs when using `--pLDDT_min` greater than 50

### ISSUE THREAD

**Issue by Rohit-Satyam** [johnnytam100/AlphaCutter#5]
I have realized that Alphacutter skips some PDBs when the `--pLDDT_min` parameters is set greater than 50. Is there a specific reason to do so?

I am testing the following PDB files from AlphaFold:

AF-Q8IFM5-F1-model_v4.pdb
AF-Q8IFM8-F1-model_v4.pdb

I also see that no matter how high I set the `--pLDDT_min` (even 90) for some reason the poor quality domains stays
See the example of the highlighted region with a low pLDDT score in Q8IFM8:

![image](https://github.com/user-attachments/assets/5d7942ad-8486-4dad-994a-a3c44b2a2e6f)

**Comment by johnnytam100** [comment]
Hi @Rohit-Satyam 

1. increasing pLDDT cutoff didn't help because, using our default parameters (I suppose where you started with), AlphaCutter treated the N-terminal non-globular helix as a domain region AND calculated the average pLDDT as a whole (i.e. together with the nice beta structure you have in this example). 

2. Therefore, please use a smaller number for `--helix_min` and `--loop_min` and further fine-tune them

e.g. `python AlphaCutter_v111.py   --loop_min 5   --helix_min 10   --fragment_min 5   --domain_min 0   --pLDDT_min 0   --local_contact_range 5   --single_out   --domain_out`

getting

![image](https://github.com/user-attachments/assets/4c795b09-8b16-40cd-a484-f97dc3495406)
